dist: bionic # use Ubuntu 18.04 as our build environment
before_install:
  - sudo apt update
  - sudo apt install python3-pip
  - cd python
install:
  - pip3 install -r requirements.txt
script:
  - mypy . # run the type checker
  - python main.py
