dist: bionic # use Ubuntu 18.04 as our build environment
language: python
python:
  - "3.7"
before_install:
  - cd python
install:
  - pip install -r requirements.txt
script:
  - mypy . # run the type checker
  - flake8 # run the code formatter
